### ISSUE TITLE
Critical bug with libs import

### ISSUE THREAD

**Issue by futured-it** [stockholmdev/logholm-python#1]
When I try to just `import logholm` - I give a ModuleNotFoundError:
```
Traceback (most recent call last):
  File "d:\Projects\Code\GitHub\logholm-python\example.py", line 1, in <module>
    import logholm
  File "d:\Projects\Code\GitHub\logholm-python\logholm\__init__.py", line 1, in <module>
    from main import log
ModuleNotFoundError: No module named 'main'
```
But in tar.gz package main.py file there is:
![image](https://user-images.githubusercontent.com/73485120/149460274-f1ace23e-c327-4dab-bb47-a8ba36baf60e.png)

**Comment by futured-it** [comment]
The bug is fixed. We have a used import main to import file, but if you need to `import file` from `__init__` file, you need to type a `.` before filename.
